#!/usr/bin/env node
/**
 * Whoply first-run setup.
 *
 *   node setup.mjs           # local dev (localhost)
 *   node setup.mjs --lan     # also reachable from phones/other PCs on your Wi-Fi
 *
 * Creates the .env files that are (correctly) NOT committed to git, so a fresh
 * clone/fork can actually boot. Safe to re-run: existing files are left alone.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { networkInterfaces } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const useLan = process.argv.includes('--lan');

/** First non-internal IPv4 address — the one other devices on the Wi-Fi can reach. */
function lanIp() {
    for (const addrs of Object.values(networkInterfaces())) {
        for (const a of addrs || []) {
            if (a.family === 'IPv4' && !a.internal) return a.address;
        }
    }
    return null;
}

const host = useLan ? lanIp() : null;
if (useLan && !host) {
    console.error('❌ Could not detect a LAN IP address. Are you connected to Wi-Fi/ethernet?');
    process.exit(1);
}
const base = host || 'localhost';

const API = `http://${base}:7000`;
const APP = `http://${base}:7200`;
const ADMIN = `http://${base}:7300`;
const FRONT = `http://${base}:7100`;

const targets = [
    {
        file: join(root, 'whoply-api', '.env'),
        label: 'whoply-api/.env',
        content: `# Local development — generated by setup.mjs. Never commit this file.
NODE_ENV=development
PORT=7000

# Local MongoDB. Using Docker? \`docker compose up -d\` starts one on this URI.
# For a shared team database, paste your MongoDB Atlas URI here instead.
MONGODB_URI=mongodb://localhost:27017/whoply

# Auto-generated for this machine (min 32 chars).
JWT_SECRET=${randomBytes(48).toString('hex')}
JWT_EXPIRES_IN=7d

APP_NAME=Whoply
APP_URL=${APP}
ADMIN_URL=${ADMIN}
FRONT_URL=${FRONT}

CLOUDINARY_CLOUD_NAME=
CLOUDINARY_API_KEY=
CLOUDINARY_API_SECRET=
`,
    },
    {
        file: join(root, 'whoply-app', '.env.local'),
        label: 'whoply-app/.env.local',
        content: `# Local development — generated by setup.mjs.\nNEXT_PUBLIC_API_URL=${API}/api\n`,
    },
    {
        file: join(root, 'whoply-admin', '.env.local'),
        label: 'whoply-admin/.env.local',
        content: `# Local development — generated by setup.mjs.\nNEXT_PUBLIC_API_URL=${API}/api\n`,
    },
    {
        file: join(root, 'whoply-front', '.env.local'),
        label: 'whoply-front/.env.local',
        content: `# Local development — generated by setup.mjs.\nNEXT_PUBLIC_API_URL=${API}/api\nNEXT_PUBLIC_APP_URL=${APP}\n`,
    },
];

console.log(`\nWhoply setup — ${useLan ? `LAN mode (${host})` : 'localhost mode'}\n`);

let created = 0;
for (const t of targets) {
    if (existsSync(t.file)) {
        console.log(`  ⏭  ${t.label} already exists — left unchanged`);
        continue;
    }
    writeFileSync(t.file, t.content, 'utf8');
    console.log(`  ✅ created ${t.label}`);
    created++;
}

// Sanity: warn if a stale .env still points somewhere unreachable.
const apiEnv = join(root, 'whoply-api', '.env');
if (existsSync(apiEnv)) {
    const txt = readFileSync(apiEnv, 'utf8');
    if (/^NODE_ENV=production/m.test(txt)) {
        console.log('\n  ⚠️  whoply-api/.env has NODE_ENV=production — CORS will block localhost.');
        console.log('     Change it to `NODE_ENV=development` for local work.');
    }
    if (/JWT_SECRET=change-me/.test(txt)) {
        console.log('\n  ⚠️  whoply-api/.env still has the placeholder JWT_SECRET — the API will refuse to start.');
        console.log('     Replace it with: node -e "console.log(require(\'crypto\').randomBytes(48).toString(\'hex\'))"');
    }
}

console.log(`\n${created ? `Created ${created} file(s).` : 'Nothing to create.'}\n`);
console.log('Next steps:');
console.log('  1. Start MongoDB       →  docker compose up -d      (or install MongoDB locally)');
console.log('  2. cd whoply-api && npm install && npm run seed && npm run dev');
console.log('  3. cd whoply-app && npm install && npm run dev');
if (useLan) {
    console.log(`\n  Open from your phone:  ${APP}`);
    console.log('  (Allow Node.js through your firewall for ports 7000/7200 when Windows asks.)');
}
console.log('');
